spring.application.name=stour
spring.data.mongodb.host=103.81.94.201
spring.data.mongodb.port=27020
spring.data.mongodb.database=ladi_stour
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=admin
spring.data.mongodb.password=123456a@A
